spring.application.name=esportdotaznik
server.port=8069
spring.datasource.url=jdbc:postgresql://db-postgresql-fra1-98956-esport-do-user-8302199-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require
spring.datasource.username=doadmin

spring.flyway.user=doadmin

spring.flyway.locations=classpath:db.migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=3

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
